@startuml LAMIO
skinparam svgLinkTarget _blank
left to right direction
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 20
skinparam rectangle {
	BackgroundColor #FFF9F5
	BorderColor #C46A44
}
skinparam arrowColor #555555
scale 0.60
rectangle "Frames (x_1..x_t, x_{t+1})" as IN
rectangle "Latent Actions (ã_1..ã_t)" as OUT
rectangle "Latent Action Model" as LAM {
	rectangle "ST Seq\nEncoder" as L1
	rectangle "VQ\nQuantize" as L2
	L1 --> L2
}
IN --> L1
L2 --> OUT
@enduml
